FROM harbor.intgdc.com/staging/graphene-firefox:69.0-0.25.0-2.3.8

ARG GIT_COMMIT=unspecified
LABEL image_name="Graphene Firefox Image for Testing Trial"
LABEL maintainer="ATT Scrum <lhv-auto@gooddata.com>"
LABEL git_repository_url="https://github.com/gooddata/graphene-tests"
LABEL parent_image="harbor.intgdc.com/staging/graphene-firefox:69.0-0.25.0-2.3.8"
LABEL git_commit=$GIT_COMMIT

ARG RUBY_SDK_VERSION=2.1.3

#==================
# GoodData Ruby SDK
#==================
RUN chmod o=x /root
RUN gem install gooddata -v $RUBY_SDK_VERSION --bindir /usr/local/bin
