FROM harbor.intgdc.com/base/gdc-base-centos:7b4dcf6

ARG GIT_COMMIT=unspecified
LABEL image_name="Graphene Firefox Image"
LABEL maintainer="ATT Scrum <lhv-auto@gooddata.com>"
LABEL git_repository_url="https://github.com/gooddata/graphene-tests"
LABEL parent_image="harbor.intgdc.com/base/gdc-base-centos:7b4dcf6"
LABEL git_commit=$GIT_COMMIT

ARG BROWSER_VERSION=60.0.1
ARG DRIVER_VERSION=0.20.1

#=========
# Firefox
#=========
RUN set -x && \
    yum clean all && \
    yum install --setopt=tsflags=nodocs -y xorg-x11-server-Xvfb xorg-x11-xinit \
                dejavu-sans-fonts dejavu-sans-mono-fonts dejavu-serif-fonts \
                maven-bin which bzip2 firefox gtk3-devel && \
    echo "checklist_image" | md5sum |cut -f1 -d\ > /etc/machine-id && \
    yum remove -y firefox && \
    rm -rf /opt/firefox

# download and install firefox
RUN curl https://download-installer.cdn.mozilla.net/pub/firefox/releases/$BROWSER_VERSION/linux-x86_64/en-US/firefox-$BROWSER_VERSION.tar.bz2 > /tmp/firefox-$BROWSER_VERSION.tar.bz2 && \
    tar -C /opt -xjf /tmp/firefox-$BROWSER_VERSION.tar.bz2 && \
    rm /tmp/firefox-$BROWSER_VERSION.tar.bz2 && \
    mv /opt/firefox /opt/firefox-$BROWSER_VERSION && \
    ln -fs /opt/firefox-$BROWSER_VERSION/firefox /usr/bin/firefox && \
    yum clean all && rm -rf /var/cache/yum

#============
# GeckoDriver
#============
RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v$DRIVER_VERSION/geckodriver-v$DRIVER_VERSION-linux64.tar.gz > /tmp/geckodriver-v$DRIVER_VERSION-linux64.tar.gz && \
    tar -C /opt -zxf /tmp/geckodriver-v$DRIVER_VERSION-linux64.tar.gz && \
    rm /tmp/geckodriver-v$DRIVER_VERSION-linux64.tar.gz && \
    mv /opt/geckodriver /opt/geckodriver-$DRIVER_VERSION && \
    chmod 755 /opt/geckodriver-$DRIVER_VERSION && \
    ln -fs /opt/geckodriver-$DRIVER_VERSION /usr/bin/geckodriver
