# (C) 2020 GoodData Corporation
version: "3.7"

services:
  acceptance-tests:
    image: ${IMAGE_ID}
    environment:
      HOME: /graphene-tests
    volumes:
      - .:/graphene-tests
      - $HOME/.m2:/tmp/.m2
    working_dir: /graphene-tests
    user: '$USER_UID:$USER_GID'
    shm_size: '4gb'
    command: |
      sh -c '
      ./integration-mvn-test.sh \
      -DbrowserDownloadFolder=/graphene-tests/Downloads \
      -Dtest.execution.env=local-edge \
      -DedgeDriverBinaryPath=/bin/msedgedriver \
      -pl ui-tests-core,ui-tests-indigo/ui-tests-ad,ui-tests-indigo/ui-tests-dashboards \
      -Dtestng.suite.xml=acceptance-tests.xml \
      -Dhost=att-graphene.dev.intgdc.com \
      -Duser=bear@gooddata.com \
      -Dpassword=jindrisska \
      -Duser.domain=default \
      -Dproject.authorizationToken=pgroup2 \
      -Dproject.dwhDriver=pg \
      -DdeleteMode=delete_if_successful \
      -DuseDynamicUser=true \'
