package com.gooddata.qa.graphene.enums;

public enum LcmDirectoryConfiguration {

    GD_ENDCODE_PARAM("gd_encoded_params", "gd_encoded_params"),
    CLIENT_GDC_HOSTNAME("CLIENT_GDC_HOSTNAME", "staging-lcm-prod.intgdc.com"),
    GDC_PASSWORD("GDC_PASSWORD", "GDC_PASSWORD"),
    ORGANIZATION("organization", "default"),
    ADS_PASSWORD("ads_password", "ads_password"),
    GDC_USERNAME("GDC_USERNAME", "GDC_USERNAME"),
    CLIENT_GDC_PROTOCOL("CLIENT_GDC_PROTOCOL", "https"),
    GDC_LOG_LEVEL("GDC_LOG_LEVEL", "DEBUG"),
    GD_ENDCODE_HIDEN_PARAMS("gd_encoded_hidden_params", "gd_encoded_hidden_params"),
    EXCLUDE_FACT_RULE("exclude_fact_rule", "true"),
    TRANSFER_ALL("transfer_all", "true"),
    SEGMENT_ID("SEGMENT_ID", "segement_id"),
    JDBC_URL("JDBC_URL", "jbbc_url"),
    DEVELOPMENT_PID("DEVELOPMENT_PID", "development_pid"),
    MASTER_PROJECT_NAME("mstpn", "master_project_name"),
    TOKEN_ID("TOKEN", "token_id"),
    SNOWFLAKE_USER_NAME("SNOWFLAKE_USER_NAME", "SNOWFLAKE_USER_NAME"),
    REDSHIFT_USER_NAME("REDSHIFT_USER_NAME", "REDSHIFT_USER_NAME"),
    POSTGRES_USER_NAME("POSTGRES_USER_NAME", "POSTGRES_USER_NAME"),
    SNOWFLAKE_PASSWORD("SNOWFLAKE_PASSWORD", "SNOWFLAKE_PASSWORD"),
    REDSHIFT_PASSWORD("REDSHIFT_PASSWORD", "REDSHIFT_PASSWORD"),
    POSTGRES_PASSWORD("POSTGRES_PASSWORD", "POSTGRES_PASSWORD"),
    SNOWFLAKE_URL("SNOWFLAKE_URL", "SNOWFLAKE_URL"),
    REDSHIFT_URL("REDSHIFT_URL", "REDSHIFT_URL"),
    BIGQUERY_URL("BIGQUERY_URL", "BIGQUERY_URL"),
    POSTGRE_URL("POSTGRES_URL", "POSTGRES_URL"),
    SNOWFLAKE_DATABASE("SNOWFLAKE_DATABASE", "SNOWFLAKE_DATABASE"),
    SNOWFLAKE_SCHEMA("SNOWFLAKE_SCHEMA", "SNOWFLAKE_SCHEMA"),
    SNOWFLAKE_WAREHOUSE("SNOWFLAKE_WAREHOUSE", "SNOWFLAKE_WAREHOUSE"),
    REDSHIFT_DATABASE("REDSHIFT_DATABASE", "REDSHIFT_DATABASE"),
    REDSHIFT_SCHEMA("REDSHIFT_SCHEMA", "REDSHIFT_SCHEMA"),
    POSTGRE_DATABASE("POSTGRES_DATABASE", "POSTGRES_DATABASE"),
    POSTGRE_SCHEMA("POSTGRES_SCHEMA", "POSTGRES_SCHEMA"),
    POSTGRE_SSL_MODE("POSTGRES_SSL_MODE", "POSTGRES_SSL_MODE"),
    BIGQUERY_CLIENT_EMAIL("BIGQUERY_CLIENT_EMAIL", "BIGQUERY_CLIENT_EMAIL"),
    BIGQUERY_PRIVATE_KEY("BIGQUERY_PRIVATE_KEY", "BIGQUERY_PRIVATE_KEY"),
    BIGQUERY_SCHEMA("BIGQUERY_SCHEMA", "BIGQUERY_SCHEMA"),
    BIGQUERY_PROJECT("BIGQUERY_PROJECT", "BIGQUERY_PROJECT"),
    DATA_PRODUCT("DATA_PRODUCT", "att_lcm_default_data_product");

    private String paramName;
    private String paramValue;

    private LcmDirectoryConfiguration(String paramName, String paramValue) {
        this.paramName = paramName;
        this.paramValue = paramValue;
    }

    public String getParamName() {
        return paramName;
    }
    public String getParamValue() {
        return paramValue;
    }

}
